# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: New Book of Old Hymns
email: newbook@brandt.id.au
description: A collection of Gregorian chant hymns plus extra related music making a handy collection in a little yellow paperback book with an Imprimatur.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.brandt.id.au/newbookoldhymns"
twitter_username: veromarybrrr
github_username:  veromary

# Build settings
markdown: kramdown
