# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: New Book of Old Hymns
email: newbook@brandt.id.au
description: A collection of Gregorian chant hymns plus extra related music making a handy collection in a little yellow paperback book with an Imprimatur.
baseurl: "/newbookoldhymns"
url: ""
facebook_username: newbookoldhymns
github_username:  veromary
twitter_username:  veromarybrrr
disqus: brandtlab

# Build settings
markdown: kramdown
google_analytics: UA-39801667-1

collections:
  hymns:
    output: true
  gloss:
    output: true

